# Generated by Django 3.2.15 on 2022-09-08 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(default='', max_length=30)),
                ('created_date', models.DateTimeField(editable=False)),
                ('modified_by', models.CharField(default='', max_length=30)),
                ('modified_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('modeltemplate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.modeltemplate')),
                ('proposal_name', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
                ('proposal_date', models.DateField()),
            ],
            bases=('api.modeltemplate',),
        ),
    ]
