# Generated by Django 3.2.15 on 2022-09-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeltemplate',
            name='modified_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='proposal_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
